
export const NPM_SET_PACKAGES = 'NPM_SET_PACKAGES';
export const NPM_RETRIEVE_STATS = 'NPM_RETRIEVE_STATS';
export const NPM_UPDATE_INTERVAL_DATA = 'NPM_UPDATE_INTERVAL_DATA';
export const NPM_RETRIEVE_HISTORY = 'NPM_RETRIEVE_HISTORY';
export const NPM_CHANGE_PERIOD = 'NPM_CHANGE_PERIOD';
export const NPM_CHANGE_INTERVAL = 'NPM_CHANGE_INTERVAL';

