
export const NPM_SET_PACKAGES = 'NPM_SET_PACKAGES';
export const NPM_RETRIEVE_STATS = 'NPM_RETRIEVE_STATS';
export const NPM_REMOVE_PACKAGE = 'NPM_REMOVE_PACKAGE';
export const NPM_ADD_PACKAGE = 'NPM_ADD_PACKAGE';
export const NPM_RETRIEVE_HISTORY = 'NPM_RETRIEVE_HISTORY';
export const NPM_RETRIEVE_SEARCH = 'NPM_RETRIEVE_SEARCH';
export const NPM_UPDATE_SEARCH = 'NPM_UPDATE_SEARCH';
export const NPM_CLEAR_SEARCH = 'NPM_CLEAR_SEARCH';
export const NPM_CHANGE_PERIOD = 'NPM_CHANGE_PERIOD';
export const NPM_CHANGE_INTERVAL = 'NPM_CHANGE_INTERVAL';

