export const NPM_RETRIEVE_STATS = 'NPM_RETRIEVE_STATS';
export const NPM_REMOVE_PACKAGE = 'NPM_REMOVE_STATS';
export const NPM_RETRIEVE_HISTORY = 'NPM_RETRIEVE_HISTORY';
export const NPM_RETRIEVE_SEARCH = 'NPM_RETRIEVE_SEARCH';
